# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.java.installations.fromEnv=JAVA_21_HOME

modID=hexal
modName=Hexal
modVersion=0.3.1

curseforgeId=824725
modrinthId=aBVJ6Q36

jetbrainsAnnotationsVersion=23.0.0

minecraftVersion=1.21.1
kotlinVersion=2.1.0

neoForgeVersion=21.1.60

loomVersion=1.8-SNAPSHOT

paucalVersion=0.7.0
# 0.12.0 corresponds to the build of 0.12.0 on CurseForge/Modrinth
hexcastingVersion=0.12.0
moreIotasVersion=0.1.1
patchouliVersion=83
geckolibVersion=4.2.1
inlineVersion=1.0.1
clothConfigVersion=11.1.106
hexdebugVersion=0.8.0

jeiVersion=15.0.0.12
pehkuiVersion=3.7.7

junitVersion=5.9.0
