modLoader="javafml"
loaderVersion="[4,)"
license="MIT"

[[mods]]
modId="hexal"
version="${file.jarVersion}"
displayName="Hexal"
displayURL="https://github.com/FallingColors/Hexal"
authors="Talia"
description='''
Hexal - an addon for Hex Casting
'''

[[dependencies.hexal]]
modId="neoforge"
type="required"
versionRange="[21.1.1,)"
ordering="NONE"
side="BOTH"

[[dependencies.hexal]]
modId="minecraft"
type="required"
versionRange="[1.21.1]"
ordering="NONE"
side="BOTH"

[[dependencies.hexal]]
modId="hexcasting"
type="required"
versionRange="*"
ordering="NONE"
side="BOTH"

[[dependencies.hexal]]
modId="paucal"
type="optional"
versionRange="*"
ordering="NONE"
side="BOTH"

[[dependencies.hexal]]
modId="patchouli"
type="optional"
versionRange="*"
ordering="NONE"
side="BOTH"

[[mixins]]
config="hexalplat.mixins.json"
