plugins {
    id 'hexal.platform'
    id 'net.neoforged.moddev' version '2.0.74-beta'
}

apply plugin: 'org.spongepowered.mixin'

archivesBaseName = getArtifactID("neoforge")

jarJar.enable()

neoForge {
    version = project.neoForgeVersion

    parchment {
        mappingsVersion = "2024.07.28"
        minecraftVersion = "1.21.1"
    }

    accessTransformers.from(file('src/main/resources/META-INF/accesstransformer.cfg'))

    runs {
        configureEach {
            systemProperty 'mixin.env.remapRefMap', 'true'
            systemProperty 'mixin.env.refMapRemappingFile', "${projectDir}/build/createSrgToMcp/output.srg"
        }

        client {
            client()
        }

        server {
            server()
        }

        data {
            data()

            programArguments.addAll '--mod', modID, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
        }
    }

    mods {
        create(modID) {
            sourceSet sourceSets.main
            sourceSet project(":Common").sourceSets.main
        }
    }
}

repositories {
    mavenCentral()

    maven {
        // location of the maven that hosts JEI files
        name = "Progwml6 maven"
        url = "https://dvs1.progwml6.com/files/maven/"
    }
    maven {
        // location of a maven mirror for JEI files, as a fallback
        name = "ModMaven"
        url = "https://modmaven.dev"
    }

    maven { url 'https://dl.cloudsmith.io/public/geckolib3/geckolib/maven/' }

    maven {
        name = 'Kotlin for Forge'
        url = 'https://thedarkcolour.github.io/KotlinForForge/'
        content { includeGroup "thedarkcolour" }
    }
}

dependencies {
    compileOnly project(":Common")

    implementation "thedarkcolour:kotlinforforge:$kotlinForForgeVersion"

    // Testing dependencies:
    testCompileOnly project(":Common")

    testCompileOnly "org.junit.jupiter:junit-jupiter-api:$junitVersion"
    testRuntimeOnly "org.junit.jupiter:junit-jupiter-engine:$junitVersion"
}

mixin {
    add sourceSets.main, "hexal.mixins.refmap.json"
    add sourceSets.test, "hexal.test.mixins.refmap.json"
    config "hexalplat.mixins.json"
    config "hexal_forge.mixins.json"
}

tasks.withType(JavaCompile) {
    source(project(":Common").sourceSets.main.allSource)
}
compileKotlin {
    source(project(":Common").sourceSets.main.kotlin)
}
compileTestKotlin {
    source(project(":Common").sourceSets.test.kotlin)
}

tasks.jarJar {
    archiveClassifier = ""
}

jar {
    archiveClassifier = "slim"
}

tasks.register("ciArtifacts", Copy) {
    from tasks.jarJar
    into rootProject.file("build/ciArtifacts")
}

build {
    println "Forcing re-compile of Java to include refmap"
    tasks.withType(JavaCompile) {
        outputs.upToDateWhen { false }
    }
    compileKotlin {
        outputs.upToDateWhen { false }
    }
    dependsOn ciArtifacts
}

sourceSets {
    main.resources.srcDirs += ['src/generated/resources', '../Common/src/generated/resources']
    test.resources.srcDirs += ['src/generated/resources', '../Common/src/generated/resources', 'src/main/resources', '../Common/src/main/resources']
    main.kotlin.srcDirs += 'src/main/java'
    test.kotlin.srcDirs += 'src/main/java'
}

processResources {
    from project(":Common").sourceSets.main.resources
    inputs.property "version", project.version

    filesMatching("mods.toml") {
        expand "version": project.version
    }
}

processTestResources {
    from project(":Common").sourceSets.test.resources
    inputs.property "version", project.version

    filesMatching("mods.toml") {
        expand "version": project.version
    }
}

publishMods {
    file = tasks.jarJar.archiveFile
}

setupJar(this)

publishing {
    publications {
        mavenJava(MavenPublication) {
            artifact tasks.jarJar
        }
    }
}
